### Estrutura  de Dados

##### Dicionários

<img src="../imgs/notebooks/dict.png" style="max-width:300px; "/>

In [1]:
dict_morse = {".-": "A", "-...": "B", "-.-.": "C", "-..": "D", ".": "E", "..-.": "F","--.": "G", "....": "H", "..": "I", ".---": "J", "-.-": "K", ".-..": "L","--": "M", "-.": "N", "---": "O", ".--.": "P", "--.-": "Q", ".-.": "R","...": "S", "-": "T", "..-": "U", "...-": "V", ".--": "W", "-..-": "X","-.--": "Y", "--..": "Z", "-----": 0, ".----": 1, "..---": 2, "...--": 3,"....-": 4, ".....": 5, "-....": 6, "--...": 7, "---..": 8, "----.": 9}

In [2]:
print(dict_morse)

{'.-': 'A', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z', '-----': 0, '.----': 1, '..---': 2, '...--': 3, '....-': 4, '.....': 5, '-....': 6, '--...': 7, '---..': 8, '----.': 9}


In [7]:
# Itens, chaves, valores
print(dict_morse.items())
print(dict_morse.keys())
print(dict_morse.values())

dict_items([('.-', 'A'), ('-...', 'B'), ('-.-.', 'C'), ('-..', 'D'), ('.', 'E'), ('..-.', 'F'), ('--.', 'G'), ('....', 'H'), ('..', 'I'), ('.---', 'J'), ('-.-', 'K'), ('.-..', 'L'), ('--', 'M'), ('-.', 'N'), ('---', 'O'), ('.--.', 'P'), ('--.-', 'Q'), ('.-.', 'R'), ('...', 'S'), ('-', 'T'), ('..-', 'U'), ('...-', 'V'), ('.--', 'W'), ('-..-', 'X'), ('-.--', 'Y'), ('--..', 'Z'), ('-----', 0), ('.----', 1), ('..---', 2), ('...--', 3), ('....-', 4), ('.....', 5), ('-....', 6), ('--...', 7), ('---..', 8), ('----.', 9)])
dict_keys(['.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', '.----', '..---', '...--', '....-', '.....', '-....', '--...', '---..', '----.'])
dict_values(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [10]:
# conferindo o tipo
type(dict_morse.values())

dict_values

In [11]:
type(dict_morse)

dict

In [13]:
# conferindo o tamanho
print(len(dict_morse))
print(len(dict_morse.values()))

36
36


**Acessando e Manipulando Dados**

In [14]:
# acessando um valor através de uma chave
dict_morse['.-']

'A'

In [16]:
type(dict_morse['.-'])

str

In [18]:
type(dict_morse["..---"])
print(dict_morse["..---"])

2


In [19]:
dict_morse.get("..---")

2

**Operações**

In [22]:
# Imprimir os valores de uma dicionário
dict_morse.keys()

dict_keys(['.-', '-...', '-.-.', '-..', '.', '..-.', '--.', '....', '..', '.---', '-.-', '.-..', '--', '-.', '---', '.--.', '--.-', '.-.', '...', '-', '..-', '...-', '.--', '-..-', '-.--', '--..', '-----', '.----', '..---', '...--', '....-', '.....', '-....', '--...', '---..', '----.'])

In [29]:
for key in dict_morse:
    print(f"Chave: {key}, valor : {dict_morse[key]}")

Chave: .-, valor : A
Chave: -..., valor : B
Chave: -.-., valor : C
Chave: -.., valor : D
Chave: ., valor : E
Chave: ..-., valor : F
Chave: --., valor : G
Chave: ...., valor : H
Chave: .., valor : I
Chave: .---, valor : J
Chave: -.-, valor : K
Chave: .-.., valor : L
Chave: --, valor : M
Chave: -., valor : N
Chave: ---, valor : O
Chave: .--., valor : P
Chave: --.-, valor : Q
Chave: .-., valor : R
Chave: ..., valor : S
Chave: -, valor : T
Chave: ..-, valor : U
Chave: ...-, valor : V
Chave: .--, valor : W
Chave: -..-, valor : X
Chave: -.--, valor : Y
Chave: --.., valor : Z
Chave: -----, valor : 0
Chave: .----, valor : 1
Chave: ..---, valor : 2
Chave: ...--, valor : 3
Chave: ....-, valor : 4
Chave: ....., valor : 5
Chave: -...., valor : 6
Chave: --..., valor : 7
Chave: ---.., valor : 8
Chave: ----., valor : 9


In [30]:
# Adicionando e removendo itens
dict_morse["teste"] = 32

In [32]:
dict_morse.pop("teste")
print(dict_morse)

{'.-': 'A', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z', '-----': 0, '.----': 1, '..---': 2, '...--': 3, '....-': 4, '.....': 5, '-....': 6, '--...': 7, '---..': 8, '----.': 9}


In [35]:
# Alterando valores de um dicionário
dict_morse['.-'] = 'A'

#### Listas

<img src="../imgs/notebooks/lists.png" style="max-width:500px; "/>

In [36]:
lst_values = list(dict_morse.values())
print(lst_values)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


**Acessando e Manipulando Dados**

In [41]:
#lista[indice]
#lista[inicio:parada]
print(
    f" {lst_values[0]} \n",
    f"{lst_values[0:5]} \n",
    f"{lst_values[-1]} \n",
    f"{type(lst_values[-1])}"
)

 A 
 ['A', 'B', 'C', 'D', 'E'] 
 9 
 <class 'int'>


In [42]:
# lista[inicio:parada:passo] 
lst_values[0:10:2]

['A', 'C', 'E', 'G', 'I']

**Operações**

In [43]:
# Concatenação
lst_values[:5] + lst_values[-3:]

['A', 'B', 'C', 'D', 'E', 7, 8, 9]

In [45]:
# Alterando elementos
lst_values[0] = "G"
lst_values[0]
lst_values[0] = "A"
lst_values[0]

'A'

In [47]:
# Adicionando elementos a lista
lst_values.append("olá")
print(lst_values)
lst_values.append(12)
print(lst_values)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'olá', 'olá']
['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'olá', 'olá', 12]


In [51]:
# Encontrando a posição de um elemento
lst_values.pop(37)
print(lst_values)
lst_values.remove("olá")
print(lst_values)

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [53]:
# Removend elementos da lista
lst = ['A', 'B', 'C', 'D', 'E', 7, 8, 9]
lst.clear()
lst

[]

In [54]:
# Multidimensionalidade
mult_lst = [lst_values[:5], lst_values[-5:]] 
mult_lst

[['A', 'B', 'C', 'D', 'E'], [5, 6, 7, 8, 9]]

In [55]:
mult_lst[0]

['A', 'B', 'C', 'D', 'E']

In [56]:
# count
lst = ['A', 'B', 'C', 'D', 'E', 7, 8, 9, 'A','A', 7]
print(lst.count(7))
print(lst.count('A'))
print(lst.count('C'))

2
3
1


In [57]:
#Sum
sum([ 1,2,3])

6

In [58]:
# sort
sorted([ 1,9,2,5,3,12])

[1, 2, 3, 5, 9, 12]

In [62]:
txt = "Carolina"
txt[0]

'C'

In [63]:
txt[0] = "M"

TypeError: 'str' object does not support item assignment

Ainda temos um "tipo especial de listas" que são os arrays

- https://docs.python.org/pt-br/3.7/library/array.html
- https://numpy.org/doc/stable/reference/generated/numpy.array.html

In [64]:
import array
import numpy as np

**Arrays**

In [65]:
arr = array.array('i', [1, 2, 3])

In [66]:
arr[0]

1

In [67]:
arr.append("olá")

TypeError: 'str' object cannot be interpreted as an integer

In [68]:
print([5, 10, 15]*2)

[5, 10, 15, 5, 10, 15]


**Numpy**

In [70]:
arr1 = np.array([5, 10, 15])
arr2 = np.array([2, 5, 10])
print(arr1 + arr2)

[ 7 15 25]


In [71]:
print(arr1 - arr2)
print(arr1 * 2)

[3 5 5]
[10 20 30]


**List Comprehension**

In [72]:
valores = [-5, 7, 1, 0, 10, 100, 33, 2]

In [73]:
# Com for
quadrados = []
for v in valores:
    quadrados.append(v**2)
print(quadrados)


[25, 49, 1, 0, 100, 10000, 1089, 4]


In [74]:
# Com list comprehension
[v**2 for v in valores]

[25, 49, 1, 0, 100, 10000, 1089, 4]

In [75]:
import time

In [76]:
# Comparando a performance listas e np arrays

a = time.time()
L = range(1000000)
[i**2 for i in L]
print(time.time() - a)

a = time.time()
b = np.arange(1000000)
b**2
print(time.time() - a)


0.14107990264892578
0.005003213882446289


#### Tuplas

In [82]:
tuple_values = tuple(lst_values)
print(tuple_values)

('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9)


In [83]:
type(tuple_values) 

tuple

In [84]:
# Acessando dados
print(tuple_values[0:2])
print(tuple_values[-1]) 

('A', 'B')
9


In [85]:
# Operações
print((1,2) + (3,4))

(1, 2, 3, 4)


In [86]:
# imutabilidade
tuple_values[0] = "AA"

TypeError: 'tuple' object does not support item assignment

In [87]:
import timeit

lista_teste = timeit.timeit(stmt='[1,2,3,4,5]', number=1_000_000)
tupla_teste = timeit.timeit(stmt='(1,2,3,4,5)', number=1_000_000)
print(f'Tempo da lista: {lista_teste}') 
print(f'Tempo da tupla: {tupla_teste}')

Tempo da lista: 0.061467899940907955
Tempo da tupla: 0.014197700191289186


#### Conjuntos

In [88]:
cj = set('cachorro')
cj

{'a', 'c', 'h', 'o', 'r'}

In [89]:
type(cj)

set

In [90]:
# criando set a partir de uma lista
set(list('cachorro'))

{'a', 'c', 'h', 'o', 'r'}

**Acessando e manipulando dados**

In [91]:
cj[0]

TypeError: 'set' object is not subscriptable

In [92]:
len("cachorro")
len(cj)

5

In [93]:
cj.add("2")
print(cj)
cj.discard("2")
print(cj)

{'r', 'o', 'a', 'c', 'h', '2'}
{'r', 'o', 'a', 'c', 'h'}


**Operações**

In [95]:
alfabeto = {'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J',
    'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T',
    'U','V', 'W', 'X', 'Y', 'Z'}
set_values = set(dict_morse.values())

<img src="../imgs/notebooks/set_intersection.png" style="max-width:500px; "/>

In [98]:
# Interseção
print(set_values & alfabeto)
print(set_values.intersection(alfabeto))

{'O', 'J', 'A', 'D', 'N', 'W', 'U', 'L', 'M', 'F', 'Z', 'Q', 'Y', 'R', 'G', 'H', 'C', 'V', 'I', 'T', 'X', 'B', 'P', 'K', 'E', 'S'}
{'O', 'J', 'A', 'D', 'N', 'W', 'U', 'L', 'M', 'F', 'Z', 'Q', 'Y', 'R', 'G', 'H', 'C', 'V', 'I', 'T', 'X', 'B', 'P', 'K', 'E', 'S'}


<img src="../imgs/notebooks/set_diff.png" style="max-width:500px; "/>

In [99]:
#Diferença
print(set_values  - alfabeto) 
print(set_values.difference(alfabeto)) 
print(alfabeto - set_values) 
print(alfabeto.difference(set_values))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
set()
set()


<img src="../imgs/notebooks/set_diff_sim.png" style="max-width:500px; "/>

In [100]:
# Diferença simétrica
print(set_values.symmetric_difference(alfabeto))
print(alfabeto.symmetric_difference(set_values))
print(set_values ^ alfabeto)
print(alfabeto ^ set_values)

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


<img src="../imgs/notebooks/set_union.png" style="max-width:500px; "/>

In [101]:
# união
print({"cc", "xx"}| alfabeto) 
print({"cc", "xx"}.union(alfabeto))

{'O', 'C', 'J', 'V', 'I', 'T', 'X', 'H', 'B', 'xx', 'A', 'D', 'P', 'N', 'K', 'W', 'U', 'L', 'M', 'F', 'Z', 'Q', 'E', 'Y', 'R', 'S', 'G', 'cc'}
{'O', 'C', 'J', 'V', 'I', 'T', 'X', 'H', 'B', 'xx', 'A', 'D', 'P', 'N', 'K', 'W', 'U', 'L', 'M', 'F', 'Z', 'Q', 'E', 'Y', 'R', 'S', 'G', 'cc'}


#### Resumo

- Listas: Coleção ordenada e mutável. Permite membros duplicados.
- Tuplas: Coleção ordenada e imutável. Permite membros duplicados.
- Sets: Coleção não-ordenada e não-indexada. Não permite membros duplicados.
- Dicionários: Coleção não-ordenada, mutável e indexável. Não permite membros duplicados.